name = "highrise-slack-worker"
main = "src/index.js"
compatibility_date = "2023-01-12"
node_compat = true
compatibility_flags = [
  "streams_enable_constructors"
]
kv_namespaces = [
  { binding = "HIGHRISE_SYNC_KV", id = "226b384e54d841ad96e10ecbac8115eb", preview_id = "723aa08a4f2c45d58a0e93d4d6841057" }
]

[triggers]
crons = [ "*/15 * * * *" ]

[vars]
# HIGHRISE_TOKEN - Highrise API token
# HIGHRISE_URL - Base URL for Highrise API requests
# SLACK_URL - Slack webhook URL for channel
# HIGHRISE_GROUPS - Only include records visible to these highrise groups (comma-separated list)
# EVERYONE - set to 'TRUE' to include records visible to everyone in sync
