name = "highrise-slack-staging"
main = "src/index.js"
account_id = "058b57748d31e63e7bfdb0f690cb8ba7"
compatibility_date = "2023-01-12"
node_compat = true
# compatibility_flags = [
#   "streams_enable_constructors"
# ]
kv_namespaces = [
  { binding = "HIGHRISE_SYNC_KV", id = "226b384e54d841ad96e10ecbac8115eb", preview_id = "723aa08a4f2c45d58a0e93d4d6841057" }
]

[triggers]
crons = [ "*/15 * * * *" ]

[env.fundraising]
name = "highrise-slack-fundraising"
kv_namespaces = [
  { binding = "HIGHRISE_SYNC_KV", id = "226b384e54d841ad96e10ecbac8115eb", preview_id = "723aa08a4f2c45d58a0e93d4d6841057" }
]

[env.fundraising.vars]
HIGHRISE_URL = "https://ddem.highrisehq.com/"
ENVIRONMENT = "fundraising"
EVERYONE = "FALSE"
HIGHRISE_GROUPS = "463829"

[env.programs]
name = "highrise-slack-programs"
kv_namespaces = [
  { binding = "HIGHRISE_SYNC_KV", id = "226b384e54d841ad96e10ecbac8115eb", preview_id = "723aa08a4f2c45d58a0e93d4d6841057" }
]

[env.programs.vars]
HIGHRISE_URL = "https://ddem.highrisehq.com/"
ENVIRONMENT = "programs"
EVERYONE = "TRUE"
HIGHRISE_GROUPS = "684498"

[vars]
HIGHRISE_URL = "https://ddem.highrisehq.com/"
# HIGHRISE_TOKEN - Highrise API token
# SLACK_URL - Slack webhook URL for channel
# HIGHRISE_GROUPS - Only include records visible to these highrise groups (comma-separated list)
# EVERYONE - set to 'TRUE' to include records visible to everyone in sync
